export const READ_ALL_CLIENTS = "READ_ALL_CLIENTS"
export const ADD_CLIENT = "ADD_CLIENT"
export const EDIT_CLIENT = "EDIT_CLIENT"
export const DELETE_CLIENT = "DELETE_CLIENT"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
