//Login
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"

// Clients
export const READ_ALL_CLIENTS = "READ_ALL_CLIENTS"
export const READ_CLIENTS_TOTAL_AMOUNT = "READ_CLIENTS_TOTAL_AMOUNT"
export const ADD_CLIENT = "ADD_CLIENT"
export const EDIT_CLIENT = "EDIT_CLIENT"
export const DELETE_CLIENT = "DELETE_CLIENT"
export const EDIT_CLIENT_AMOUNT = "EDIT_CLIENT_AMOUNT"
export const POST_CHARGES_TO_CLIENTS = "POST_CHARGES_TO_CLIENTS"

//Employees
export const READ_ALL_EMPLOYEES = "READ_ALL_EMPLOYEES"
export const ADD_EMPLOYEE = "ADD_EMPLOYEE"
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE"
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE"


//Payments
export const READ_ALL_CHARGES = "READ_ALL_CHARGES"
export const ADD_CHARGE = "ADD_CHARGE"
export const DELETE_CHARGE = "DELETE_CHARGE"
export const EDIT_CHARGE = "EDIT_CHARGE"
